# Generated by Django 4.2.5 on 2023-09-14 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpnj', models.CharField(max_length=50)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('area_de_atuacao', models.CharField(max_length=50)),
                ('tempo_atuacao_mercado', models.IntegerField()),
                ('capital_social', models.DecimalField(decimal_places=2, max_digits=9)),
                ('n_func_clt', models.IntegerField()),
                ('n_func_terc', models.IntegerField()),
                ('n_estagiario', models.IntegerField()),
                ('n_socios', models.IntegerField()),
                ('razao_social', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=50, null=True)),
                ('instagram', models.CharField(max_length=50, null=True)),
                ('facebook', models.CharField(max_length=50, null=True)),
                ('twitter', models.CharField(max_length=50, null=True)),
                ('linkedin', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.companymodel')),
            ],
        ),
    ]
