# Generated by Django 4.2.5 on 2023-09-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_invoicingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='razao_social',
            field=models.CharField(max_length=100),
        ),
    ]
