# Generated by Django 4.2.5 on 2023-09-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_companymodel_empresario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
