# Generated by Django 4.2.5 on 2023-09-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_partnermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='nome_socios',
            field=models.TextField(null=True),
        ),
    ]
