# Generated by Django 4.2.5 on 2023-09-15 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_companymodel_empresario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicingmodel',
            name='company',
            field=models.IntegerField(),
        ),
    ]
