# Generated by Django 4.2.5 on 2023-09-15 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_invoicingmodel_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicingmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companymodel'),
        ),
    ]
