# Generated by Django 4.2.5 on 2023-09-14 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companymodel')),
            ],
        ),
    ]
